[package]
name = "bcom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.17.0", features = ["persistence"] }
serialport = "4.1.0"
rfd = "0.8.2"
